# k8s/manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timstapaper
  namespace: timstapaper-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timstapaper
  template:
    metadata:
      labels:
        app: timstapaper
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: timstapaper
        image: tjsullivan1/timstapaper:sha-95fc638 # Use a specific tag for better control
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: database-url
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-creds
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-creds
              key: google-client-secret
        volumeMounts:
        - name: data-storage
          mountPath: /data
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: timstapaper-data-pvc