apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: timstapaper-route
  namespace: timstapaper-dev
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - timstapaper.sullivanenterprises.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: timstapaper-service
          port: 80
