# k8s/manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: timstapaper-service
  namespace: timstapaper-dev
spec:
  selector:
    app: timstapaper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP