name: Build and Push Docker Image

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    PROJECT_NAME: timstapaper
    PROJECT_SUBPATH: src/
    SPECIFIC_RELEASE_TAG: ${{ vars.SPECIFIC_RELEASE_TAG || '' }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Only run if the required variables exist
    if: vars.REGISTRY_LOGIN_SERVER != '' && vars.REGISTRY_LOGIN_SERVER != null
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6


      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.PROJECT_SUBPATH }}
          sbom: true
          push: true
          tags: ${{ secrets.REGISTRY_USERNAME }}/${{ env.PROJECT_NAME }}:latest

      # - name: Build registry prefix
      #   id: prefix
      #   run: |
      #     if [[ "${{ vars.REGISTRY_LOGIN_SERVER }}" == *"docker.io"* ]]; then
      #       echo "prefix=${{ vars.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.PROJECT_NAME }}" >> $GITHUB_OUTPUT
      #     else
      #       echo "prefix=${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME }}" >> $GITHUB_OUTPUT
      #     fi


      # - run: |
      #       if [ -z "${{ env.SPECIFIC_RELEASE_TAG }}" ]; then
      #           docker buildx build --sbom=true --provenance=true ${{ env.PROJECT_SUBPATH }} -t ${{ steps.prefix.outputs.prefix }}:${{ github.sha }} -t ${{ steps.prefix.outputs.prefix }}:latest
      #       else
      #           docker buildx build --sbom=true --provenance=true ${{ env.PROJECT_SUBPATH }} -t ${{ steps.prefix.outputs.prefix }}:${{ env.SPECIFIC_RELEASE_TAG }} -t ${{ steps.prefix.outputs.prefix }}:latest
      #       fi

      # - run: |
      #     docker push ${{ steps.prefix.outputs.prefix }} --all-tags
          